package com.fclarke.gameifyfitnessandtodo.network
//generated by "Generate POJO from JSON plugin"0. Projects is unused
data class Response(
	//val projects: Projects? = null,
	val items: List<ItemsItem?>? = null
)

data class ItemsItem(
	val projectId: Int? = null,
	val userId: Int? = null,
	val metaData: Any? = null,
	val taskId: Long? = null,
	val id: Long? = null,
	val legacyProjectId: Int? = null,
	var content: String? = null,
	val completedDate: String? = null
)
/*
data class Projects(
	val jsonMember942035717: JsonMember942035717? = null
)

data class JsonMember942035717(
	val shared: Boolean? = null,
	val isDeleted: Int? = null,
	val isFavorite: Int? = null,
	val color: Int? = null,
	val isArchived: Int? = null,
	val collapsed: Int? = null,
	val parentId: Any? = null,
	val name: String? = null,
	val legacyId: Int? = null,
	val id: Int? = null,
	val syncId: Any? = null,
	val childOrder: Int? = null
)
*
 */

